name: Newman Test Run
on:
  push:
    branches:
    - master
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm install -g newman
      - run: newman run "https://api.github.com/users/defunkt"
